import { type DBSchema } from "idb";
import { type UUID } from "crypto";

export interface Database extends DBSchema {
  data_packs: {
    key: UUID;
    value: {
      uuid?: UUID; // optional so new entries get an autogenerated ID
      name: string;
    };
  };
}

export const STORES = Object.freeze({
  DATA_PACKS: "data_packs",
  // CHARACTERS: "characters",
  // DOMAINS: "domains",
  // DOMAIN_CARDS: "domain_cards",
});
