name: Publish Daggerheart Types

on:
  push:
    tags:
      - "types-v*" # Only publish when tags like 'types-v1.0.0' are pushed
  workflow_dispatch: # Allow manual triggering
    inputs:
      version:
        description: "Version to publish"
        required: true
        default: "patch"
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup bun
        uses: oven-sh/setup-bun@v2

      - name: Setup Node.js (for npm registry auth)
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          registry-url: "https://npm.pkg.github.com"
          scope: "@jonwrona"

      - name: Install dependencies
        working-directory: packages/daggerheart-types
        run: bun install

      - name: Build types package
        working-directory: packages/daggerheart-types
        run: bun run build

      - name: Update version (if manual trigger)
        if: github.event_name == 'workflow_dispatch'
        working-directory: packages/daggerheart-types
        run: npm version ${{ github.event.inputs.version }} --no-git-tag-version

      - name: Publish to GitHub Packages
        working-directory: packages/daggerheart-types
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create release (if manual trigger)
        if: github.event_name == 'workflow_dispatch'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: types-v${{ steps.version.outputs.new_version }}
          release_name: Daggerheart Types v${{ steps.version.outputs.new_version }}
          body: |
            Published Daggerheart Types package to GitHub Packages

            ## Installation
            ```bash
            npm install @your-username/daggerheart-types
            ```
          draft: false
          prerelease: false
